<?php return array(
	'plugin.blog.postsListTag'=>'Etiquette',
	'plugin.blog.Posts:'=>'Billets :',
	'plugin.blog.Posts'=>'Billets',
	'plugin.blog.Post'=>'Billet',
	'plugin.blog.Authors:'=>'Auteurs :',
	'plugin.blog.Authors'=>'Auteurs',
	'plugin.blog.Tags'=>'Etiquettes',
	'plugin.blog.Tags:'=>'Etiquettes :',
	'plugin.blog.Tag'=>'Etiquette',
	'plugin.blog.Categories'=>'Catégories',
	'plugin.blog.Categorie'=>'Catégorie',
	'plugin.blog.Comments'=>'Commentaires',
	'plugin.blog.Comment'=>'Commentaire',
	'plugin.blog.CommentValidation'=>'Validation des commentaires',
	'plugin.blog.Tools'=>'Outils',
	'plugin.blog.tagCloud'=>'Nuage d\'étiquettes',
	'plugin.blog.post_Tag'=>'Mots clés de l\'article',
	'plugin.blog.readMore'=>'Lire la suite...',
	'plugin.blog.permalink'=>'Permalien',
	'plugin.blog.PublishedOn'=>'Publié le',
	'plugin.blog.updatedOn'=>'mis à jour le',
	'plugin.blog.LatestPosts'=>'Derniers billets',
	'plugin.blog.editPost'=>'Modifer ce billet',
	'plugin.blog.postLinked_title'=>'Billets liés',
	'plugin.blog.PostsLatestTitle'=>'Derniers billets',
	'plugin.blog.NoComments'=>'Pas de commentaire',
);
