<?php return array(
	'plugin.searchable.LinkedTerms'=>'Termes liés',
	'plugin.searchable.LinkedKeywords'=>'Mots-clés liés',
	'models.Searchables:id'=>'Id',
	'models.Searchables:name'=>'Nom',
	'models.Searchables:normalized'=>'Nom normalisé',
	'models.Searchables:order'=>'Order',
	'models.Searchables:slug'=>'Slug',
	'models.Searchables:visible'=>'Visible',
	'models.SearchablesTerm:id'=>'Id',
	'models.SearchablesTerm:term'=>'Terme',
	'models.SearchablesTypedTerm:type.Enum.None'=>'Aucun',
	'models.SearchablesTypedTerm:type.Enum.Keyword'=>'Mot-clé',
	'models.SearchablesTypedTerm:type.Enum.Masculine noun'=>'Nom masculin',
	'models.SearchablesTypedTerm:type.Enum.Feminin noun'=>'Nom féminin',
	'models.SearchablesTypedTerm:type.Enum.Plural noun'=>'Nom pluriel',
	'models.SearchablesTypedTerm:type.Enum.Epicene'=>'Épicène',
	'models.SearchablesTypedTerm:type.Enum.Abbreviation'=>'Abréviation',
	'models.SearchablesTypedTerm:type.Enum.Acronym'=>'Acronyme',
	'models.SearchablesTypedTerm:type.Enum.Spelling mistake'=>'Erreur orth.',
);
