<?php return array(
	'plugin.searchable.LinkedTerms'=>'Linked terms',
	'plugin.searchable.LinkedKeywords'=>'Linked keywords',
	'plugin.searchable.Abbreviations'=>'Abbreviations',
	'models.Searchables:id'=>'Id',
	'models.Searchables:name'=>'Name',
	'models.Searchables:normalized'=>'Normalized name',
	'models.Searchables:order'=>'Order',
	'models.Searchables:slug'=>'Slug',
	'models.Searchables:visible'=>'Visible',
	'models.SearchablesTerm:id'=>'Id',
	'models.SearchablesTerm:term'=>'Term',
	'models.SearchablesTypedTerm:type.Enum.None'=>'None',
	'models.SearchablesTypedTerm:type.Enum.Keyword'=>'Keyword',
	'models.SearchablesTypedTerm:type.Enum.Masculine term'=>'Masculine term',
	'models.SearchablesTypedTerm:type.Enum.Feminin term'=>'Feminin term',
	'models.SearchablesTypedTerm:type.Enum.Plural term'=>'Plural term',
	'models.SearchablesTypedTerm:type.Enum.Epicene'=>'Epicene',
	'models.SearchablesTypedTerm:type.Enum.Adjective'=>'Adjective',
	'models.SearchablesTypedTerm:type.Enum.Abbreviation'=>'Abbreviation',
	'models.SearchablesTypedTerm:type.Enum.Acronym'=>'Acronym',
	'models.SearchablesTypedTerm:type.Enum.Spelling mistake'=>'Spelling mistake',
);
