<?php return array(
	'plugin.searchable.LinkedTerms'=>'Linked terms',
	'plugin.searchable.LinkedKeywords'=>'Linked keywords',
	'models.Searchables:id'=>'Id',
	'models.Searchables:name'=>'Name',
	'models.Searchables:normalized'=>'Normalized name',
	'models.Searchables:order'=>'Order',
	'models.Searchables:slug'=>'Slug',
	'models.Searchables:visible'=>'Visible',
	'models.SearchablesTerm:id'=>'Id',
	'models.SearchablesTerm:term'=>'Term',
	'models.SearchablesTerm:type.Enum.None'=>'None',
	'models.SearchablesTerm:type.Enum.Main'=>'Main',
	'models.SearchablesTerm:type.Enum.Masculine noun'=>'Masculine noun',
	'models.SearchablesTerm:type.Enum.Feminin noun'=>'Feminin noun',
	'models.SearchablesTerm:type.Enum.Plural noun'=>'Plural noun',
	'models.SearchablesTerm:type.Enum.Spelling mistake'=>'Spelling mistake',
	'models.SearchablesTerm:type.Enum.Epicene'=>'Epicene',
);
